/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import model.ConnectionBuilder;
import model.Review;

/**
 *
 * @author VatcharaCK
 */
public class DataReview extends javax.swing.JFrame {
    
    public static String review_id;
    public static String username;
    public static String resName;
    public static String topic;
    public static String content;
    public static String score;

    public static String getReview_id() {
        return review_id;
    }

    public static void setReview_id(String review_id) {
        DataReview.review_id = review_id;
    }

    public static String getUsername() {
        return username;
    }

    public static void setUsername(String username) {
        DataReview.username = username;
    }

    public static String getResName() {
        return resName;
    }

    public static void setResName(String resName) {
        DataReview.resName = resName;
    }

    public static String getTopic() {
        return topic;
    }

    public static void setTopic(String topic) {
        DataReview.topic = topic;
    }

    public static String getContent() {
        return content;
    }

    public static void setContent(String content) {
        DataReview.content = content;
    }

    public static String getScore() {
        return score;
    }

    public static void setScore(String score) {
        DataReview.score = score;
    }

    
     
    public DataReview() {
        initComponents();
        try{
            labelRest.setText(HomeGUI.getResNameFromTable()); //ใส่ชื่อร้าน
            System.out.println("Restaurant: "+HomeGUI.getResNameFromTable()+"\tReview id: "+getReview_id());
            labelUsername.setText(getUsername());
            labelReviewId.setText(getReview_id());
            labelTopic.setText(getTopic());
            labelscore.setText(getScore());
            txtAreaComment.setText(getContent());
//            labelComment.setText(getContent());
            String path = Review.selectImageURL(getReview_id());
            System.out.println("Path image: "+Review.getImageURL());
            labelImage.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(250,170,Image.SCALE_DEFAULT)));           
        }catch(Exception e){
            
            e.printStackTrace();
        }   
//        jLabel1.setIcon(new ImageIcon(new ImageIcon(Review.selectpic()).getImage().getScaledInstance(241, 169,Image.SCALE_DEFAULT)));
//               
//            System.out.println("TLabel6"+getRvId());
//        } catch (SQLException ex) {
//            System.out.println(ex.getMessage());;
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTopic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelscore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaComment = new javax.swing.JTextArea();
        labelReviewId = new javax.swing.JLabel();
        labelRest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(110, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelImage.setText("IMAGE HERE");
        jPanel1.add(labelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 241, 169));

        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label1.setText("Review By  :");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 100, 38));

        labelUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelUsername.setText("username");
        jPanel1.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 130, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Topic :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, 41));

        labelTopic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTopic.setText("too");
        jPanel1.add(labelTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 330, 41));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Score :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 33));

        labelscore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelscore.setText("X.XX");
        jPanel1.add(labelscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, 33));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Comment: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, 31));

        txtAreaComment.setEditable(false);
        txtAreaComment.setColumns(20);
        txtAreaComment.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAreaComment.setLineWrap(true);
        txtAreaComment.setRows(3);
        txtAreaComment.setTabSize(2);
        jScrollPane1.setViewportView(txtAreaComment);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 160));

        labelReviewId.setText("XX");
        jPanel1.add(labelReviewId, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 20, -1));

        labelRest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelRest.setForeground(new java.awt.Color(255, 255, 255));
        labelRest.setText("Restaurant name");
        labelRest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(labelRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
//        tbProduct.setFillsViewportHeight(true);
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataReview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelRest;
    private javax.swing.JLabel labelReviewId;
    private javax.swing.JLabel labelTopic;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelscore;
    private javax.swing.JTextArea txtAreaComment;
    // End of variables declaration//GEN-END:variables
}
