/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Review;
import model.User;
import GUI.LoginGUI;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author peemtnp
 */
public class ReviewResGUI extends javax.swing.JFrame {

    HomeGUI h = null;
    String pathimg = "";

    public ReviewResGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtFldResID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFldTopic = new javax.swing.JTextField();
        txtFldContent = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        comboLook = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboService = new javax.swing.JComboBox<>();
        comboTaste = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboClean = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        comboWorth = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtFldUsername = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Myproject\\Picture\\Untitled-1.jpg")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setBackground(new java.awt.Color(0, 153, 0));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("ส่ง");
        btnCreate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnCreate.setPreferredSize(new java.awt.Dimension(60, 35));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 492, 71, 47));

        btnBack.setIcon(new javax.swing.ImageIcon("D:\\Myproject\\Picture\\กลับ.jpg")); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnBack.setPreferredSize(new java.awt.Dimension(60, 35));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 504, -1, -1));

        txtFldResID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFldResID.setText("Restaurant ID");
        txtFldResID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        txtFldResID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFldResIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFldResIDFocusLost(evt);
            }
        });
        txtFldResID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldResIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtFldResID, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 94, 352, 40));

        jLabel12.setFont(new java.awt.Font("Pattaya", 0, 18)); // NOI18N
        jLabel12.setText("หัวข้อรีวิว");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 147, 120, 39));

        jLabel13.setFont(new java.awt.Font("Pattaya", 0, 18)); // NOI18N
        jLabel13.setText("เขียนรัวิวที่นี่");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 246, 120, 39));

        txtFldTopic.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtFldTopic.setForeground(new java.awt.Color(102, 102, 102));
        txtFldTopic.setText("topic");
        txtFldTopic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        txtFldTopic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFldTopicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFldTopicFocusLost(evt);
            }
        });
        txtFldTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldTopicActionPerformed(evt);
            }
        });
        jPanel1.add(txtFldTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 193, 352, 40));

        txtFldContent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFldContent.setForeground(new java.awt.Color(51, 51, 51));
        txtFldContent.setText("comment");
        txtFldContent.setToolTipText("");
        txtFldContent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        txtFldContent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFldContentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFldContentFocusLost(evt);
            }
        });
        txtFldContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldContentActionPerformed(evt);
            }
        });
        jPanel1.add(txtFldContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 292, 352, 162));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboLook.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboLook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "คะแนน", "0", "1", "2", "3", "4", "5" }));
        comboLook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel2.add(comboLook, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 200, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 102, 204));
        jLabel7.setFont(new java.awt.Font("Pattaya", 0, 18)); // NOI18N
        jLabel7.setText("รสชาติ(0-5)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, 120, 39));

        jLabel9.setFont(new java.awt.Font("Pattaya", 0, 18)); // NOI18N
        jLabel9.setText("ความสะอาด(0-5)");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, 120, 39));

        comboService.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "คะแนน", "0", "1", "2", "3", "4", "5" }));
        comboService.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel2.add(comboService, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 156, -1, -1));

        comboTaste.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboTaste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "คะแนน", "0", "1", "2", "3", "4", "5" }));
        comboTaste.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        comboTaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTasteActionPerformed(evt);
            }
        });
        jPanel2.add(comboTaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 64, -1, -1));

        jLabel8.setFont(new java.awt.Font("Pattaya", 0, 18)); // NOI18N
        jLabel8.setText("การบริการ(0-5)");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 120, 39));

        jLabel11.setFont(new java.awt.Font("Pattaya", 0, 18)); // NOI18N
        jLabel11.setText("บรรยากาศ(0-5)");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 195, 120, 39));

        comboClean.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboClean.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "คะแนน", "0", "1", "2", "3", "4", "5" }));
        comboClean.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel2.add(comboClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Pattaya", 0, 18)); // NOI18N
        jLabel10.setText("ความคุ้มค่า(0-5)");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 241, 120, 39));

        comboWorth.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboWorth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "คะแนน", "0", "1", "2", "3", "4", "5" }));
        comboWorth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel2.add(comboWorth, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 246, -1, -1));

        jLabel14.setFont(new java.awt.Font("Pattaya", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("ให้คะแนนร้านค้า");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 177, 39));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 193, -1, -1));

        txtFldUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFldUsername.setText("username");
        txtFldUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.lightGray));
        txtFldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFldUsernameFocusLost(evt);
            }
        });
        txtFldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 13, 352, 40));

        img.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        img.setText("       image");
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 180, 110));

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Input image here: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        JOptionPane.showMessageDialog(null,"Complete");
        
        System.out.println("Selected CreateButton");
       
        String username = txtFldUsername.getText();
        int resId = Integer.parseInt(txtFldResID.getText());
        String topic = txtFldTopic.getText();
        String content = txtFldContent.getText();
        int taste = Integer.parseInt(comboTaste.getSelectedItem().toString());
        int clean = Integer.parseInt(comboClean.getSelectedItem().toString());
        int service = Integer.parseInt(comboService.getSelectedItem().toString());
        int look = Integer.parseInt(comboLook.getSelectedItem().toString());
        int worth = Integer.parseInt(comboWorth.getSelectedItem().toString());

        try {
            ArrayList<Review> rev = Review.reviewRes(username, resId, topic, content, taste, clean, service, look, worth);
            ArrayList<Review> img = Review.imgin(pathimg);
        } catch (SQLException ex) {
            //            Logger.getLogger(ReviewGUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("! SQL ReviewGUI");
        } catch (ClassNotFoundException ex) {
            //            Logger.getLogger(ReviewGUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("!! ClassNotFound ReviewGUI");
        }
        int conf = JOptionPane.showConfirmDialog(null, "Go to homepage?", "Confirm Dialog", 2);
        if (conf == 0) {
            System.out.println("You Press OK...Go to Homepage");
            try {
                h = new HomeGUI();
            } catch (SQLException ex) {
                Logger.getLogger(ReviewResGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ReviewResGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            h.setVisible(true);
            this.setVisible(false);
        } else {
            System.out.println("You Press Cancel...Stay this page");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//        HomeGUI h = null;
        try {
            h = new HomeGUI();
        } catch (SQLException ex) {
            Logger.getLogger(ReviewResGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReviewResGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFldResIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldResIDFocusGained
        if (txtFldResID.getText().equalsIgnoreCase("Restaurant ID")) {
            txtFldResID.setText("");
        } else {
        }
    }//GEN-LAST:event_txtFldResIDFocusGained

    private void txtFldResIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldResIDFocusLost
        if (txtFldResID.getText().equalsIgnoreCase("")) {
            txtFldResID.setText("Restaurant ID");
        } else {
        }
    }//GEN-LAST:event_txtFldResIDFocusLost

    private void txtFldResIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldResIDActionPerformed

    }//GEN-LAST:event_txtFldResIDActionPerformed

    private void txtFldTopicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldTopicFocusGained
        if (txtFldTopic.getText().equalsIgnoreCase("topic")) {
            txtFldTopic.setText("");
        } else {
        }
    }//GEN-LAST:event_txtFldTopicFocusGained

    private void txtFldTopicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldTopicFocusLost
        if (txtFldTopic.getText().equalsIgnoreCase("")) {
            txtFldTopic.setText("topic");
        }
    }//GEN-LAST:event_txtFldTopicFocusLost

    private void txtFldTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldTopicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldTopicActionPerformed

    private void txtFldContentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldContentFocusGained
        if (txtFldContent.getText().equalsIgnoreCase("comment")) {
            txtFldContent.setText("");
        }
    }//GEN-LAST:event_txtFldContentFocusGained

    private void txtFldContentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldContentFocusLost
        if (txtFldContent.getText().equalsIgnoreCase("")) {
            txtFldContent.setText("comment");
        }
    }//GEN-LAST:event_txtFldContentFocusLost

    private void txtFldContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldContentActionPerformed

    private void txtFldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldUsernameFocusGained

        if (txtFldResID.getText().equalsIgnoreCase("Username")) {
            txtFldResID.setText("");
        } else {
        }
    }//GEN-LAST:event_txtFldUsernameFocusGained

    private void txtFldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldUsernameFocusLost
        if (txtFldUsername.getText().equalsIgnoreCase("")) {
            txtFldUsername.setText("Username");
        }
    }//GEN-LAST:event_txtFldUsernameFocusLost

    private void txtFldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldUsernameActionPerformed

    private void comboTasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTasteActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser fileopen = new JFileChooser();  //AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
       fileopen.setAcceptAllFileFilterUsed(false);
       fileopen.addChoosableFileFilter(new FileNameExtensionFilter(".jpg","jpg"));
       fileopen.addChoosableFileFilter(new FileNameExtensionFilter(".gif","gif"));
       fileopen.addChoosableFileFilter(new FileNameExtensionFilter(".png","png"));
       int result = fileopen.showDialog(null,"Choose Picture");
       if(result == JFileChooser.APPROVE_OPTION){
           File selectfile = fileopen.getSelectedFile();
           String path = selectfile.getAbsolutePath();
           img.setIcon(new ImageIcon((new ImageIcon(path).getImage().getScaledInstance(120, 80,Image.SCALE_DEFAULT))));
           pathimg = path;
            System.out.println(pathimg);
          
       }
    }//GEN-LAST:event_btnBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewResGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewResGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewResGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewResGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewResGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> comboClean;
    private javax.swing.JComboBox<String> comboLook;
    private javax.swing.JComboBox<String> comboService;
    private javax.swing.JComboBox<String> comboTaste;
    private javax.swing.JComboBox<String> comboWorth;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFldContent;
    private javax.swing.JTextField txtFldResID;
    private javax.swing.JTextField txtFldTopic;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables
}
